# Generated by Django 4.2.11 on 2024-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='category_data',
            field=models.CharField(blank=True, choices=[('writer', 'Book Writer'), ('publisher', 'Book Publisher'), ('book', 'Book')], max_length=50),
        ),
        migrations.AlterField(
            model_name='writer',
            name='category_data',
            field=models.CharField(blank=True, choices=[('writer', 'Book Writer'), ('publisher', 'Book Publisher'), ('book', 'Book')], max_length=50),
        ),
    ]
