# Generated by Django 4.2.11 on 2024-05-02 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.CharField(default='Kecamatan', max_length=50)),
                ('subdistrict', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.province')),
            ],
        ),
    ]
